name: 'CICD with MSSQL - Destroy'

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./CICD with MSSQL/Azure

jobs:
  destroy-dev:
    name: 'DEV'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform detroy
      uses: "./.github/templates/terraform-apply"
      with:
        WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
        BACKEND_CONFIG: backend.dev.conf
        VARIABLES: -var="environment=dev" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}

  destroy-uat:
    name: 'UAT'
    runs-on: ubuntu-latest
    environment: UAT
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform detroy
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="${{ vars.AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ env.AZURE_TENANT_ID }}"

        terraform init -backend-config="configuration/backend.uat.conf"
        terraform destroy -var="environment=uat" -var="password=${{ secrets.AZURE_DB_PASSWORD }}" -auto-approve

  destroy-prd:
    name: 'PRD'
    runs-on: ubuntu-latest
    environment: PRD
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform detroy
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="${{ vars.AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ env.AZURE_TENANT_ID }}"

        terraform init -backend-config="configuration/backend.prd.conf"
        terraform destroy -var="environment=prd" -var="password=${{ secrets.AZURE_DB_PASSWORD }}" -auto-approve
