name: 'CICD with MSSQL - Deploy'

on:
  push:
    branches:
    - main
    paths:
    - 'CICD with MSSQL/Azure/**/*.tf'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./CICD with MSSQL/Azure

jobs:
  deploy-dev:
    name: 'DEV'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="${{ vars.AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ vars.AZURE_TENANT_ID }}"
        export TF_LOG="trace"
        
        terraform init -backend-config="configuration/backend.dev.conf"
        terraform apply -auto-approve -var="environment=dev" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  deploy-uat:
    name: 'UAT'
    runs-on: ubuntu-latest
    environment: UAT
    needs: [deploy-dev]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="${{ vars.AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ vars.AZURE_TENANT_ID }}"

        terraform init -backend-config="configuration/backend.uat.conf"
        terraform apply -auto-approve -var="environment=uat" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  deploy-prd:
    name: 'PRD'
    runs-on: ubuntu-latest
    environment: PRD
    needs: [deploy-uat]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="${{ vars.AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ vars.AZURE_TENANT_ID }}"

        terraform init -backend-config="configuration/backend.prd.conf"
        terraform apply -auto-approve -var="environment=prd" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"
