name: 'CICD with MSSQL - Destroy'

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./CICD with MSSQL/Azure

jobs:
  destroy-dev:
    name: 'DEV'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_ENVIRONMENT: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform Init
      run: terraform init -backend-config="configuration/backend.${{ env.TF_ENVIRONMENT }}.conf"
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var="environment=${{ env.TF_ENVIRONMENT }}" -var="spn=${{ secrets.AZURE_SPN_ID }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  destroy-uat:
    name: 'UAT'
    runs-on: ubuntu-latest
    environment: UAT
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_ENVIRONMENT: uat
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform Init
      run: terraform init -backend-config="configuration/backend.${{ env.TF_ENVIRONMENT }}.conf"
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var="environment=${{ env.TF_ENVIRONMENT }}" -var="spn=${{ secrets.AZURE_SPN_ID }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  destroy-prd:
    name: 'PRD'
    runs-on: ubuntu-latest
    environment: PRD
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_ENVIRONMENT: prd
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform Init
      run: terraform init -backend-config="configuration/backend.${{ env.TF_ENVIRONMENT }}.conf"
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var="environment=${{ env.TF_ENVIRONMENT }}" -var="spn=${{ secrets.AZURE_SPN_ID }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"
