name: 'CICD with MSSQL - Deploy'

on:
  push:
    branches:
    - main
    paths:
    - 'CICD with MSSQL/Azure/**/*.tf'
  workflow_dispatch:

jobs:
  deploy-dev:
    name: 'DEV'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="166adf1d-3776-4c73-b613-fa3f4a29f0a8"
        export ARM_TENANT_ID="806f47be-2b6d-4478-9283-7f354e840d82"

        terraform init -backend-config="configuration/backend.dev.conf"
        terraform apply -auto-approve -var="environment=dev" -var="password=${{ secrets.AZURE_DB_PASSWORD_DEV }}"

  deploy-uat:
    name: 'UAT'
    runs-on: ubuntu-latest
    environment: UAT
    needs: [deploy-dev]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="166adf1d-3776-4c73-b613-fa3f4a29f0a8"
        export ARM_TENANT_ID="806f47be-2b6d-4478-9283-7f354e840d82"

        terraform init -backend-config="configuration/backend.uat.conf"
        terraform apply -auto-approve -var="environment=uat" -var="password=${{ secrets.AZURE_DB_PASSWORD_PRD }}"

  deploy-prd:
    name: 'PRD'
    runs-on: ubuntu-latest
    environment: PRD
    needs: [deploy-uat]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: terraform fmt -check -recursive
    - name: Terraform deployment
      run: |
        export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
        export ARM_SUBSCRIPTION_ID="166adf1d-3776-4c73-b613-fa3f4a29f0a8"
        export ARM_TENANT_ID="806f47be-2b6d-4478-9283-7f354e840d82"

        terraform init -backend-config="configuration/backend.prd.conf"
        terraform apply -auto-approve -var="environment=prd" -var="password=${{ secrets.AZURE_DB_PASSWORD_PRD }}"
