name: 'CICD with MSSQL - Destroy'

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./CICD with MSSQL/Azure

jobs:
  destroy-dev:
    name: 'DEV'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform destroy
      uses: "./.github/templates/terraform"
      with:
        TYPE: destroy
        WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        BACKEND_CONFIG: backend.dev.conf
        VARIABLES: -var="environment=dev" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  destroy-uat:
    name: 'UAT'
    runs-on: ubuntu-latest
    environment: UAT
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform destroy
      uses: "./.github/templates/terraform"
      with:
        TYPE: destroy
        WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        BACKEND_CONFIG: backend.uat.conf
        VARIABLES: -var="environment=uat" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"

  destroy-prd:
    name: 'PRD'
    runs-on: ubuntu-latest
    environment: PRD
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform destroy
      uses: "./.github/templates/terraform"
      with:
        TYPE: destroy
        WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        BACKEND_CONFIG: backend.uat.conf
        VARIABLES: -var="environment=uat" -var="password=${{ secrets.AZURE_DB_PASSWORD }}"
